name: Auditoria de Qualidade de Software

on:
  push:
    branches: [Testes/Auditoria]
  pull_request:
    branches: [Testes/Auditoria]

jobs:
  qualidade:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ§° Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¦ Instalar dependÃªncias
        run: npm install

      - name: ğŸ§ª Rodar testes com cobertura
        run: npm test -- --coverage

      - name: ğŸ“Š Analisar com SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
